name: calling reusable pipeline

on: 
  push:
    branches:
      - '*'

jobs:
  execute-pipeline:
    uses: leytoncasta/test-gitHub-actions/.github/workflows/reusable_pipeline.yml@main
    with: 
      node-version: 14