name: calling reusable pipeline

on: 
  push:
    branches:
      - '*'

jobs:
  execute-pipeline:
    uses: test-gitHub-actions/.github/workflows/resusable_pipeline.yml@feature
    with: 
      node-version: 14